include:
 - 'https://source.puri.sm/Librem5/librem5-ci/raw/master/librem5-pipeline-definitions.yml'

stages:
  - build
  - test
  - package
  - test-package

.tags: &tags
  tags:
    - librem5

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -y update
  - apt-get -y install build-essential wget ca-certificates gnupg
  - echo "deb http://ci.puri.sm/ scratch librem5" > /etc/apt/sources.list.d/ci.list
  - wget -O- https://ci.puri.sm/ci-repo.key | apt-key add -
  - apt-get -y update
  - apt-get -y build-dep .

build-debian-gcc-buster:
  <<: *tags
  image: debian:buster
  stage: build
  script:
    - export LC_ALL=C.UTF-8
    - meson . _build --werror
    - ninja -C _build
  artifacts:
    paths:
      - _build

build-debian-gcc-bullseye:
  <<: *tags
  image: debian:bullseye
  stage: build
  script:
    - export LC_ALL=C.UTF-8
    - meson . _build --werror
    - ninja -C _build
  artifacts:
    paths:
      - _build

test:debian-gcc:
  <<: *tags
  stage: test
  dependencies:
    - build-debian-gcc-buster
  script:
    - export G_DEBUG=fatal-warnings
    - export LC_ALL=C.UTF-8
    - ninja -C _build test

package:deb-debian-buster:
  extends: .l5-build-debian-package

package:deb-debian-buster:arm64:
  tags:
    - librem5:arm64
  extends: .l5-build-debian-package

autopkgtest-debian-buster-package:
  dependencies:
    - package:deb-debian-buster
  extends: .l5-autopkgtest-debian-package

lintian-debian-buster-package:
  dependencies:
    - package:deb-debian-buster
  extends: .l5-lintian-debian-package

