include:
  - 'https://source.puri.sm/Librem5/librem5-ci/raw/master/librem5-pipeline-definitions.yml'
  - project: 'gnome/citemplates'
    file: 'flatpak/flatpak-ci-initiative-sdk-extensions.yml'

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  IMAGE: debian:trixie

stages:
  - build
  - test
  - package
  - test-package

.tags: &tags
  tags:
    - librem5

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -y update

build-debian-gcc-trixie-no-purple:
  image: debian:trixie
  stage: build
  script:
    - apt-get -y build-dep .
    - apt-get -y install git
    - export LC_ALL=C.UTF-8
    - meson setup _build -Dpurple=disabled
    - meson compile -C _build

build-debian-gcc-trixie:
  image: debian:trixie
  stage: build
  script:
    - apt-get -y build-dep .
    - apt-get -y install libgtk-4-bin xvfb git
    - export LC_ALL=C.UTF-8
    - meson setup _build -Db_coverage=true --werror
    - meson compile -C _build
  artifacts:
    paths:
      - _build

test:debian-gcc:
  stage: test
  image: debian:trixie
  dependencies:
    - build-debian-gcc-trixie
  script:
    - apt-get -y build-dep .
    - apt-get -y install libgtk-4-bin xvfb gcovr git
    - export G_DEBUG=fatal-warnings
    - export LC_ALL=C.UTF-8
    - xvfb-run -a -s "-screen 0 1024x768x24" ninja -C _build test
    - ninja -C _build coverage
  coverage: '/^\s+lines\.+:\s+([\d.]+\%)\s+/'

check-po:
  stage: test
  image: debian:bullseye
  dependencies:
    - build-debian-gcc-trixie
  before_script:
    - apt-get -y update
    - apt-get -y install intltool git
  script:
    # barf on untranslated C files. Seems intltool
    # can't be told to exit with non-zero exit status
    # in this case
    - cd po/
    - intltool-update -m 2>&1 | grep -qs '/.*\.\(c\|ui\)' && { intltool-update -m; exit 1; } || exit 0

package:deb-debian-trixie:arm64:
  variables:
    L5_DOCKER_IMAGE: debian:trixie
    DEB_BUILD_PROFILES: "nodoc nocheck"
    DEB_BUILD_OPTIONS: nocheck
  extends: .l5-build-debian-package
  tags:
    - aarch64
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -y update
    - apt-get -y install eatmydata

flatpak:
  before_script: []
  extends: ".flatpak"
  variables:
    APP_ID: "sm.puri.Chatty.Devel"
    BUNDLE: "sm.puri.Chatty.Devel.flatpak"
    FLATPAK_MODULE: "chatty"
    MANIFEST_PATH: "sm.puri.Chatty.json"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"

