include:
  - 'https://source.puri.sm/Librem5/librem5-ci/raw/master/librem5-pipeline-definitions.yml'
  - project: 'gnome/citemplates'
    file: 'flatpak/flatpak-ci-initiative-sdk-extensions.yml'

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  IMAGE: debian:trixie
  ALPINE_IMAGE: alpine:edge

stages:
  - build
  - test
  - package
  - test-package

.tags: &tags
  tags:
    - librem5

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -y update

build-debian-gcc-trixie-no-purple:
  image: ${IMAGE}
  stage: build
  script:
    - apt-get -y build-dep .
    - apt-get -y install git
    - export LC_ALL=C.UTF-8
    - meson setup _build -Dpurple=disabled
    - meson compile -C _build
  except:
    variables:
      - $FP_ONLY == "1"

build-debian-gcc-trixie:
  image: ${IMAGE}
  stage: build
  script:
    - apt-get -y build-dep .
    - apt-get -y install libgtk-4-bin xvfb git
    - export LC_ALL=C.UTF-8
    - meson setup _build -Db_coverage=true --werror
    - meson compile -C _build
  artifacts:
    paths:
      - _build
  except:
    variables:
      - $FP_ONLY == "1"

build-alpine-edge:
  image: ${ALPINE_IMAGE}
  stage: build
  before_script:
    - apk -q add
        build-base
        glib-dev
        dbus
        dbus-x11
        evolution-data-server-dev
        evolution-dev
        feedbackd-dev
        folks-dev
        gspell-dev
        gnupg
        gst-plugins-base-dev
        gtk+3.0-dev
        libadwaita-dev
        libgee-dev
        libphonenumber-dev
        meson
        modemmanager-dev
        olm-dev
        pidgin-dev
        cyrus-sasl
        purple-xmpp
        purple-carbons
        purple-lurch
        purple-xmpp-http-upload
        appstream-glib
        desktop-file-utils
        mesa-dri-gallium
        xvfb-run
  script:
    # check for uninitialized g_autoptr, which cause segfaults in musl
    - grep -n -e 'g_autoptr(\w*)\s*\w*;' -R . && exit 1
    - meson setup -Dwerror=true _build
    - meson compile -C _build
  artifacts:
    paths:
      - _build/

test:debian-gcc:
  stage: test
  image: ${IMAGE}
  dependencies:
    - build-debian-gcc-trixie
  script:
    - apt-get -y build-dep .
    - apt-get -y install libgtk-4-bin xvfb gcovr git
    - export G_DEBUG=fatal-warnings
    - export LC_ALL=C.UTF-8
    - xvfb-run -a -s "-screen 0 1024x768x24" ninja -C _build test
# Disable until it works in trixie again
#    - ninja -C _build coverage
  coverage: '/^\s+lines\.+:\s+([\d.]+\%)\s+/'
  except:
    variables:
      - $FP_ONLY == "1"

test:alpine-edge:
  stage: test
  image: ${ALPINE_IMAGE}
  dependencies:
    - build-alpine-edge
  before_script:
    - apk -q add
        build-base
        glib-dev
        dbus
        dbus-x11
        evolution-data-server-dev
        evolution-dev
        feedbackd-dev
        folks-dev
        gspell-dev
        gnupg
        gst-plugins-base-dev
        gtk+3.0-dev
        libadwaita-dev
        libgee-dev
        libphonenumber-dev
        meson
        modemmanager-dev
        olm-dev
        pidgin-dev
        cyrus-sasl
        purple-xmpp
        purple-carbons
        purple-lurch
        purple-xmpp-http-upload
        appstream-glib
        desktop-file-utils
        mesa-dri-gallium
        xvfb-run
  script:
    # check for uninitialized g_autoptr, which cause segfaults in musl
    - grep -n -e 'g_autoptr(\w*)\s*\w*;' -R . && exit 1
    - meson setup -Dwerror=true _build
    - meson compile -C _build
    - xvfb-run meson test -C _build --print-errorlogs
  artifacts:
    paths:
      - _build/

asan-test:native-debian-trixie:
  stage: test
  image: ${IMAGE}
  tags: [ asan ]
  needs: []
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -y update
    - apt-get -y build-dep .
    - apt-get -y install libgtk-4-bin xvfb gcovr git
  script:
    - meson setup -Db_sanitize=address -Dbuildtype=debug _build-asan
    - meson compile -C _build-asan
    - ${XVFB_RUN} meson test -C _build-asan --verbose  clock history settings sms-uri mm-account

check-po:
  stage: test
  image: ${IMAGE}
  dependencies:
    - build-debian-gcc-trixie
  before_script:
    - apt-get -y update
    - apt-get -y install intltool git
  script:
    # barf on untranslated C files. Seems intltool
    # can't be told to exit with non-zero exit status
    # in this case
    - cd po/
    - intltool-update -m 2>&1 | grep -qs '/.*\.\(c\|ui\|in\)' && { intltool-update -m; exit 1; } || exit 0
  except:
    variables:
      - $FP_ONLY == "1"

package:deb-debian-trixie:arm64:
  variables:
    L5_DOCKER_IMAGE: debian:trixie
    DEB_BUILD_PROFILES: "nodoc nocheck"
    DEB_BUILD_OPTIONS: nocheck
  extends: .l5-build-debian-package
  tags:
    - aarch64
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -y update
    - apt-get -y install eatmydata
  except:
    variables:
      - $FP_ONLY == "1"

flatpak-gnome-45:
  image: 'quay.io/gnome_infrastructure/gnome-runtime-images:gnome-45'
  before_script: []
  extends: ".flatpak"
  allow_failure: true
  variables:
    APP_ID: "sm.puri.Chatty.Devel"
    BUNDLE: "sm.puri.Chatty.Devel.flatpak"
    FLATPAK_MODULE: "chatty"
    MANIFEST_PATH: "sm.puri.Chatty.json"
    RUNTIME_REPO: "https://dl.flathub.org/repo/flathub.flatpakrepo"
