stages:
  - build

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -y update
  - apt-get -y install build-essential wget ca-certificates gnupg
  - echo "deb http://ci.puri.sm/ scratch librem5" > /etc/apt/sources.list.d/ci.list
  - wget -O- https://ci.puri.sm/ci-repo.key | apt-key add -
  - apt-get -y update
  - apt-get -y build-dep .

build-debian-gcc:
  image: debian:buster
  tags:
    - librem5
  stage: build
  script:
    - export LC_ALL=C.UTF-8
    - meson . _build --werror
    - ninja -C _build

build-debian-package:
  image: debian:buster
  tags:
    - librem5
  stage: build
  script:
    - dpkg-buildpackage -uc -us
